### ISSUE TITLE
Should unsync::Sender impl Clone?

### ISSUE THREAD

**Issue by davidhewitt** [Pauan/rust-dominator#1]
I just had a play around with this library tonight, I'm really enjoying it!

I came across one small pain point: I think it would be helpful if unsync::Sender also implemented Clone (like reciever). Though I'm guessing you might have omitted this on purpose?

BTW, let me know if there's anything I can do to help out. Otherwise I'll continue to play with the library and post back here with any thoughts 😸

**Comment by Pauan** [comment]
Yeah, there's still some missing stuff. For example, most of the types don't even implement `Debug`. Thanks for reminding me to fix this!

**Comment by davidhewitt** [comment]
I don't mind doing some typing here. If I made a PR would that be useful?

**Comment by Pauan** [comment]
@davidhewitt Pull requests are welcome, but for something this small I just went ahead and made the change.

I haven't thought deeply about whether `Sender` *should* implement `Clone` or not, so it might change in the future (this is still version `0.1.0` after all!)
