### ISSUE TITLE
1.0 roadmap item "Move various things into stdweb" may be stale

### ISSUE THREAD

**Issue by kellytk** [Pauan/rust-dominator#14]
As https://github.com/Pauan/rust-dominator/commit/4afde439742b79106c4c038600adc17278af5a89 has landed, should the 1.0 roadmap item be edited?

If so, how could I open a PR editing it to "Move various things into wasm-bindgen"?

**Comment by Pauan** [comment]
Oh, thanks for the reminder. I don't think it's possible for non-collaborators to edit the roadmap.

As for moving things, web-sys is basically feature-complete, so there's very little that needs to be moved: it's just `requestAnimationFrame`, the `clone` macro, and the `events` module.
