### ISSUE TITLE
Signal of HTML elements

### ISSUE THREAD

**Issue by joonazan** [Pauan/rust-dominator#20]
I'm currently using
```rust
.children_signal_vec(signal_of_elements.map(|x| vec![x]).to_signal_vec())
```
Is there a more efficient way to show a whole tag that comes out of a signal?

**Comment by thienpow** [comment]
i hope to be able to do like this... but i dunno how, 

.children_signal_vec( Route::signal().map(move |x| 
match x {
 Route::Index => [
...
],
 Route::About => [
...
]
})))

**Comment by Pauan** [comment]
@joonazan Whoops, sorry, somehow I missed your message.

I recently added in a `child_signal` method, which allows you to attach a single child element:

```rust
.child_signal(signal_of_elements.map(|x| Some(x)))
```
