### ISSUE TITLE
Fix examples in Edge

### ISSUE THREAD

**Issue by dakom** [Pauan/rust-dominator#39]
According to [the docs](https://github.com/rustwasm/wasm-bindgen/blob/master/guide/src/reference/browser-support.md) Edge requires that some polyfill for TextDecoder be installed.

I can confirm that it currently fails...

Or should Edge just not be supported? I suppose eventually everyone on old Edge will move on to Chromium-Edge...

**Comment by Pauan** [comment]
They are supported in Edge since January, and Edge auto-updates, so I'm not too worried about supporting old versions.

And the polyfills right now aren't great, so it would just add a lot of extra complexity.

**Comment by dakom** [comment]
Heh, well - my Edge has not auto-updated...

But fair enough - I think in a real-world use case it would be good enough to detect if TextEncoder is available and pop up an alert telling people to download a more modern browser instead. I'd almost consider it a public service to the netizens of the world ;)
