### ISSUE TITLE
Isomorphic web app?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Pauan/rust-dominator#41]
Hello, this project looks absolutely awesome!

I was wondering if someone could use dominator to build and isomorphic single page application using this library. From my limited knowledge I'm thinking [SSR](https://github.com/Pauan/rust-dominator/issues/29) would needed to do this but I am unsure.

**Comment by Pauan** [comment]
Yes, isomorphic is the same as SSR, so I'm going to close this is favor of that issue.
