### ISSUE TITLE
Feat: with_element method on Dom

### ISSUE THREAD

**Issue by dakom** [Pauan/rust-dominator#45]
## Problem

I have a function that receives a `Signal<Item = Option<Dom>>` and wants to render it as a child, yet it needs to sprinkle in some additional attributes first (for example a `slot` attribute)

Since there's currently no way to do that, it means creating a wrapper, and then that can introduce awkward CSS constraints that need workarounds... for example:

```rust
.child(html!("div", {
    .style("width", "100%")
    .style("height", "100%")
    .attribute("slot", "sidebar")
    .child_signal(sidebar_signal())
}))
````

## Solution

If `Dom` had a `with_element()` which accepts a `FnOnce(&web_sys::Element)`, then it would be possible to completely remove the nesting:

```rust
.child_signal(sidebar_signal()
  .map(|dom| {
    if let Some(dom) = dom {
      dom.with_element(|el| {
        el.attribute("slot", "sidebar")
      })
    }
  })
)
```

Although probably outside the scope of Dominator itself, this would then allow for easy extensions to add children to slots.

**Comment by dakom** [comment]
Closing this after discussion on Discord. Basically, this would lead to all kinds of potential breakage and spaghetti code - instead, use a DomBuilder

It can still be the responsibility of the parent to set the slot by defining the child as a component which accepts a callback function before creating the Dom.

There are many ways to approach this, but here's one example from @Pauan :

```rust
fn create_my_dom<A, F>(f: F) -> Dom
    where F: FnOnce(DomBuilder<A>) -> DomBuilder<A> {
    html!("div", {
        // ... put attributes and whatever in here ...

        // This applies the closure as a mixin
        .apply(f)
    })
}

//called in parent
create_my_dom(move |dom| {
    dom.attribute("slot", "foo")
})
```

**Comment by Pauan** [comment]
Just a note that I prefer to use components (a struct + `render` method), so it would look like this:

```rust
struct MyStruct {
    ...
}

impl MyStruct {
    fn render<F>(this: Rc<Self>, mixin: F) -> Dom
        where F: FnOnce(DomBuilder<HtmlElement>) -> DomBuilder<HtmlElement> {

        html!("div", {
            ...
            .apply(mixin)
        })
    }
}
```

And then you would call it like this:

```rust
MyStruct::render(my_struct, move |dom| {
    dom.attribute("slot", "foo")
})
```

----

And this is how it would look with the original example:

```rust
.child_signal(sidebar_signal(move |dom| {
    dom.attribute("slot", "sidebar")
}))
```
