### ISSUE TITLE
`const_generics` feature has been replaced

### ISSUE THREAD

**Issue by mpfaff** [Pauan/rust-dominator#66]
The `const_generics` feature was removed and replaced with a number of other features. As a result, dominator can no longer compile with the `nightly` feature activated. The appropriate replacement is `adt_const_params`.

**Comment by Pauan** [comment]
Thanks for the report, yeah I need to fix that.

**Comment by Pauan** [comment]
Fixed in https://github.com/Pauan/rust-dominator/commit/a893617409d198ff7eb966222eec871cbe28b58f
