### ISSUE TITLE
Add routing::replace_url

### ISSUE THREAD

**Issue by TristanCacqueray** [Pauan/rust-dominator#81]
Would it be acceptable to add a `replace_url` helper that uses `history.replace` instead of `history.push`, so that the current page is removed from the history?

**Comment by TristanCacqueray** [comment]
Looking at the code again, I would argue that calling `routing::go_to_url` directly insert history that may not match user clicks, so applications should use `link!` if possible.

**Comment by Pauan** [comment]
> I would argue that calling routing::go_to_url directly insert history that may not match user clicks, so applications should use link! if possible.

The `link!` macro internally uses `go_to_url`, it's up to the application to choose how and when it calls `go_to_url`. Applications can shoot themself in the foot if they want to, dominator won't stop them.
