### ISSUE TITLE
How to define CSS pseudo classes with ClassBuilder

### ISSUE THREAD

**Issue by rsaccon** [Pauan/rust-dominator#9]
I am trying to implement a Design System and CSS framework partially based on [TailwindCSS](https://tailwindcss.com) with the dominator `class! `(and `stylesheet!` if necessary) macros. 

Main motivation is to have typed class names and only those CSS classes which are actually used, will end up in the compiled binary (and eventually in the `CSSRuleList`).

However i got stuck at the following issue: I see no way how I could define pseudo classes with the current `ClassBuilder` and its `class!` macro.  I would like to do something like:

```rust
lazy_static! {
    static ref FOO_CLASS: String = class! {
        .style("background-color", "green")
        .style_hover("background-color", "yellow")
    };
    static ref FOO_CLASS_HOVER: String = class! {
        .base(&*FOO_CLASS)  // not implemented yet. Does it make sense ???
        .pseudo("hover")  // not implemented yet. 
        .style_hover("background-color", "yellow") 
    };
}
```

That should generate this:

```html
<style>
.__class_0__ {
    background-color: green;
}
.__class_0__:hover {
    background-color: yellow;
}
</style>
```

Is is currently possible to do something like that ?

Does the code above to implement pseudo classes make sense ? One thing I am not sure about: For the pseudo classes we need the base class name, but when the base class name gets first time accessed (inside the macro for the pseudo class), then maybe the compiler can not optimize it away anymore, in case the base class never gets used in the actual app code.

I am aware that I could build pseudo classes with `StylesheetBuilder` and its macro, but then I won't have typed class names anymore, which was my main motivation to start with all this.

**Comment by rsaccon** [comment]
Ups, somehow I confused things when I formulated out this initial issue, it turns out that it is much easier, all what is is needed is a small modification of `ClassBuilder` to allow something like this:

```rust
lazy_static! {
    static ref FOO_CLASS__HOVER: String = class! {
        .pseudo("hover")  // not implemented yet. 
        .style("background-color", "yellow") 
    };
}
```
That should generate this:

```
<style>
.__class_0__:hover {
    background-color: yellow;
}
</style>
```

will try to implement it and provide a PR

**Comment by rsaccon** [comment]
Ok, I implemented it at my fork and so far it seems to work perfectly. For pseudo classes and elements, the `class!` macro just has an additional first argument which defines the pseudo class name, see example below.
```rust
pub static ref FOO__HOVER: String = class! ("hover", {
    .style("background-color", "yellow")
  });
```
Unfortunately when I wanted to create a Pull Request, I realized that each file I modified got auto-formatted differently, that makes a PR full of noise, need to sort out that first.

**Comment by Pauan** [comment]
Hey, sorry for the delay on this (I've  spent the past few months moving to a new country). I'll look into this and your other issues soon!

**Comment by rsaccon** [comment]
No problem, no hurry, thanks anyway. 

I also run into one more issue when using `StyleSheetBuilder` when trying to do a CSS Reset based on something like [normalize.css ](http://necolas.github.io/normalize.css/)

when the rule selector is browser specific, e.g.:
```css
button::-moz-focus-inner,
[type="button"]::-moz-focus-inner,
[type="reset"]::-moz-focus-inner,
[type="submit"]::-moz-focus-inner {
  border-style: none;
  padding: 0;
}
```
then we get a panic, because (I assume) when the currently used  browser is not the targeted browser in the rule, a CSS parsing DOM exception gets thrown at [insertRule](https://github.com/Pauan/rust-dominator/blob/master/src/dom.rs#L1072):

I also built a minimalistic `wasm-bindgen` version of a CssStyleRule injector, just to troubleshoot this issue. If the insertRule fails, I just ignore it, and all seems to be fine. But I am not sure whether this is the right approach, and how to handle this in `StyleSheetBuilder`. I will further investigate, probably check how the JS libs such as [style-mod ](https://github.com/marijnh/style-mod )handle this.

**Comment by Pauan** [comment]
Okay, so I changed the `stylesheet` macro so it now can accept multiple selectors:

```rust
stylesheet!([
    "button::-moz-focus-inner",
    "button::-webkit-focus-inner",
    "button::-ms-focus-inner",
    "button::-o-focus-inner",
    "button::focus-inner",
], {
    .style("background-color", "green")
});
```

It will try each selector in order, and if a selector errors then it will try the next. As soon as a selector works then it uses it.

I also added in a `pseudo!` method for `class`, which lets you specify pseudo elements:

```rust
lazy_static! {
    static ref FOO: String = class! {
        .style("background-color", "green")

        .pseudo!(":hover", {
            .style("background-color", "red")
        })

        .pseudo!(":first", {
            .style("background-color", "orange")
        })
    };
}
```

Similar to `stylesheet` it also can accept multiple pseudos, which are tried in order until one succeeds:

```rust
.pseudo!([
    "::-moz-progress-bar",
    "::-ms-progress-bar",
    "::-o-progress-bar",
    "::-webkit-progress-bar",
    "::progress-bar",
], {
    .style("background-color", "red")
})
```
